/*
 * File: app/view/ResultadoSimplesView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GTTrans.view.ResultadoSimplesView', {
    extend: 'Ext.Panel',
    xtype:  'resultadoSimplesView',

    config: {
        scrollable: 'vertical',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Consulta de Multas SeMOB'
            },
            {
                xtype: 'fieldset',
                width: '95%',
                defaults: {
                    labelAlign: 'top',
                    readOnly: true
                },
                title: 'Veículo',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'tfPlaca',
                        label: 'Placa'
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'tfMarca',
                        label: 'Marca'
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'tfCategoria',
                        label: 'Categoria'
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'tfUf',
                        label: 'UF'
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'tfEspecie',
                        label: 'Espécie'
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'tfAutuacoes',
                        label: 'Nº de Autuações'
                    }
                ]
            }
        ]
    },

    atualizar: function(record) {
    }
});