/*
 * File: app/model/VHistoricomultas.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GTTrans.model.VHistoricomultas', {
    extend: 'Ext.data.Model',

    uses: [
        'GTTrans.model.VHistoricomultasID'
    ],

    config: {
        hasOne: {
            associatedName: 'id',
            model: 'GTTrans.model.VHistoricomultasID'
        },
        fields: [
            {
                name: 'cdSerie',
                type: 'string'
            },
            {
                name: 'dsSerie'
            },
            {
                name: 'nrConvenio'
            },
            {
                name: 'cdEspecie'
            },
            {
                name: 'nrConta'
            },
            {
                name: 'nrAit'
            },
            {
                name: 'ait'
            },
            {
                name: 'dtAit'
            },
            {
                name: 'hrAit'
            },
            {
                name: 'nrPlaca'
            },
            {
                name: 'sgUfplaca'
            },
            {
                name: 'dtLimitedefesa'
            },
            {
                name: 'dsLocal'
            },
            {
                name: 'dsComplemento'
            },
            {
                name: 'cdCategoria'
            },
            {
                name: 'nrArnait'
            },
            {
                name: 'nrArnap'
            },
            {
                name: 'nmProprietario'
            },
            {
                name: 'nmLogradouroprop'
            },
            {
                name: 'nrLogradouroprop'
            },
            {
                name: 'dsComplementoprop'
            },
            {
                name: 'nrCepprop'
            },
            {
                name: 'nrMunicipioprop'
            },
            {
                name: 'nmBairroprop'
            },
            {
                name: 'sgUfprop'
            },
            {
                name: 'cdRenainf'
            },
            {
                name: 'nrRenavan'
            },
            {
                name: 'cdMarcadetran'
            },
            {
                name: 'cdEspeciedetran'
            },
            {
                name: 'nmProprietarioveiculo'
            },
            {
                name: 'dsMarcadetran'
            },
            {
                name: 'dsEspeciedetran'
            },
            {
                name: 'vlApagar'
            },
            {
                name: 'vlPago'
            },
            {
                name: 'dtPagamento'
            },
            {
                name: 'dtVencimento'
            },
            {
                name: 'nrGuia'
            },
            {
                name: 'dsEnquadramento'
            },
            {
                name: 'cdEnquadramento'
            },
            {
                name: 'dsLei'
            },
            {
                name: 'nrPonto'
            },
            {
                name: 'vlPonto'
            },
            {
                name: 'nrLote'
            },
            {
                name: 'dtNait'
            },
            {
                name: 'dtNap'
            },
            {
                name: 'stDefesa'
            },
            {
                name: 'stRecursojari'
            },
            {
                name: 'stRecursocetran'
            },
            {
                name: 'dsCategoria'
            },
            {
                name: 'nrAgente'
            },
            {
                name: 'nrAgentevalidador'
            }
        ]
    }
});